apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aws-secrets
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "qr-generator-aws-creds"
        objectType: "secretsmanager"
  secretObjects:
  - secretName: aws-credentials
    type: Opaque
    data:
      - objectName: "qr-generator-aws-creds"
        key: AWS_ACCESS_KEY
      - objectName: "qr-generator-aws-creds"
        key: AWS_SECRET_KEY
