apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aws-secrets
  namespace: prod
spec:
  provider: aws
  parameters:
    region: "ap-south-1"
    objects: |
      - objectName: "aws-credentials"
        objectType: "secretsmanager"
  secretObjects:
    - secretName: aws-credentials
      type: Opaque
      data:
        - key: AWS_ACCESS_KEY
          objectName: AWS_ACCESS_KEY
        - key: AWS_SECRET_KEY
          objectName: AWS_SECRET_KEY