apiVersion: apps/v1
kind: Deployment
metadata:
  name: qr-generator-backend
  namespace: prod
  labels:
    app: qr-generator-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qr-generator-backend
  template:
    metadata:
      labels:
        app: qr-generator-backend
    spec:
      containers:
        - name: qr-generator-backend
          image: rahulkumarpaswan/qr-generator-backend:v1.6
          ports:
            - containerPort: 80
          env:
            - name: AWS_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: AWS_ACCESS_KEY
            - name: AWS_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: AWS_SECRET_KEY
            - name: AWS_BUCKET_NAME
              valueFrom:
                configMapKeyRef:
                  name: qr-generator-config
                  key: AWS_BUCKET_NAME

---
apiVersion: v1
kind: Service
metadata:
  name: qr-generator-backend-service
  namespace: prod
spec:
  selector:
    app: qr-generator-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
